# Generated by Django 2.1 on 2018-08-17 12:01

import cms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=190)),
                ('object_id', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('attr', 'Attribute'), ('plain', 'Plain text'), ('html', 'HTML')], default='plain', max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('content_en', models.TextField(blank=True, default='', null=True)),
                ('content_mi', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=190)),
                ('object_id', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('file', models.ImageField(blank=True, upload_to='cms/%Y_%m')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, help_text='e.g. /about/contact', max_length=255, verbose_name='URL')),
                ('template', models.CharField(default='', max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_live', models.BooleanField(default=True, help_text='If this is not checked, the page will only be visible to logged-in users.')),
            ],
            options={
                'ordering': ('url',),
            },
        ),
        migrations.CreateModel(
            name='PageSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.PositiveIntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='cms.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=190)),
                ('object_id', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('source', models.FileField(upload_to='cms/%Y_%m', validators=[cms.models.validate_video_type])),
                ('poster', models.ImageField(blank=True, upload_to='cms/%Y_%m')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('loop', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('content_type', 'object_id', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('content_type', 'object_id', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('content_type', 'object_id', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='pagesite',
            unique_together={('page', 'site_id')},
        ),
    ]
