# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20150216_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('fr', 'French'), ('es', 'Spanish'), ('pt', 'Portuguese')], default='en-us', max_length=5),
        ),
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='block',
            name='format',
            field=models.CharField(choices=[('attr', 'Attribute'), ('plain', 'Plain text'), ('html', 'HTML')], default='plain', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, upload_to='cms/%y_%m'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_live',
            field=models.BooleanField(default=True, help_text='If this is not checked, the page will only be visible to logged-in users.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(db_index=True, help_text='e.g. /about/contact', max_length=255, verbose_name='URL'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set([('content_type', 'object_id', 'language', 'label')]),
        ),
    ]
