# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20160506_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, upload_to='cms/%y_%m'),
        ),
        migrations.AlterField(
            model_name='image',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
