# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20160720_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, upload_to='cms/%Y_%m'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set([('content_type', 'object_id', 'label')]),
        ),
        migrations.RemoveField(
            model_name='block',
            name='language',
        ),
        migrations.AddField(
            model_name='block',
            name='content_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='content_zh_hans',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
