# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 15:43
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20170907_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=190)),
                ('object_id', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('source', models.FileField(upload_to='cms/%Y_%m', validators=[cms.models.validate_video_type])),
                ('poster', models.ImageField(blank=True, upload_to='cms/%Y_%m')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('loop', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set([('content_type', 'object_id', 'label')]),
        ),
    ]
