# Generated by Django 2.1.2 on 2018-11-05 11:14

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20180921_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.FileField(blank=True, upload_to='cms/%Y_%m', validators=[cms.models.validate_video_type]),
        ),
    ]
